-- =====================================================================
-- Caracalla-Thermen · Phase 8 · 01 Tabellen
-- Schema DEMO, Präfix CAR_. Jede Anweisung endet mit einer Zeile "/",
-- so läuft das Skript in SQL*Plus, SQL Developer (F5) und im Einrichter.
-- Bricht ab, wenn schon Objekte mit CAR_ vorhanden sind (dann erst 99_abbau.sql).
-- =====================================================================

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_objects WHERE object_name LIKE 'CAR\_%' ESCAPE '\';
  IF n > 0 THEN
    raise_application_error(-20801, 'Es gibt schon ' || n || ' Objekte mit CAR_. Erst 99_abbau.sql ausführen.');
  END IF;
END;
/

-- ------------------------------------------------------------- Säle
CREATE TABLE car_room (
  room_id        NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_room_pk PRIMARY KEY,
  code           VARCHAR2(30)  NOT NULL CONSTRAINT car_room_uk UNIQUE,
  name           VARCHAR2(60)  NOT NULL,
  funktion       VARCHAR2(600),
  badefolge      NUMBER(3),
  form           VARCHAR2(10)  NOT NULL CONSTRAINT car_room_form_ck CHECK (form IN ('RECHTECK', 'RUND')),
  laenge_m       NUMBER(6,2),
  breite_m       NUMBER(6,2),
  hoehe_m        NUMBER(6,2),
  ueberdacht     CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_room_ueb_ck CHECK (ueberdacht IN ('J', 'N')),
  beheizt        CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_room_beh_ck CHECK (beheizt IN ('J', 'N')),
  temp_luft_c    NUMBER(4,1),
  temp_wasser_c  NUMBER(4,1),
  nachhall_s     NUMBER(4,1),
  hall_anteil    NUMBER(3,2),
  box_x0 NUMBER(8,2), box_y0 NUMBER(8,2), box_z0 NUMBER(8,2),
  box_x1 NUMBER(8,2), box_y1 NUMBER(8,2), box_z1 NUMBER(8,2),
  radius         NUMBER(8,2),
  eye_x NUMBER(8,2), eye_y NUMBER(8,2), eye_z NUMBER(8,2),
  look_x NUMBER(8,2), look_y NUMBER(8,2), look_z NUMBER(8,2)
)
/
COMMENT ON TABLE car_room IS 'Caracalla: Säle und Höfe mit Maßen, Klima, Nachhall und Ankunftsblick (Szenenkoordinaten in m)'
/

-- ------------------------------------------------------------- Steinbrüche
CREATE TABLE car_quarry (
  quarry_id      NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_quarry_pk PRIMARY KEY,
  code           VARCHAR2(30)  NOT NULL CONSTRAINT car_quarry_uk UNIQUE,
  name_antik     VARCHAR2(80),
  name_heute     VARCHAR2(80)  NOT NULL,
  land_heute     VARCHAR2(40),
  lage           MDSYS.SDO_GEOMETRY,
  weg            MDSYS.SDO_GEOMETRY,
  weg_km         NUMBER(6),
  weg_text       VARCHAR2(600),
  quelle         VARCHAR2(400)
)
/
COMMENT ON TABLE car_quarry IS 'Caracalla: Steinbrüche (Punkt) und Transportweg nach Rom (Linie), SRID 8307'
/

-- ------------------------------------------------------------- Steinsorten
CREATE TABLE car_stone (
  stone_id       NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_stone_pk PRIMARY KEY,
  code           VARCHAR2(30)  NOT NULL CONSTRAINT car_stone_uk UNIQUE,
  name           VARCHAR2(80)  NOT NULL,
  name_antik     VARCHAR2(80),
  art            VARCHAR2(20)  NOT NULL CONSTRAINT car_stone_art_ck CHECK (art IN ('MARMOR', 'GRANIT', 'PORPHYR', 'KALKSTEIN', 'SERPENTIN')),
  quarry_id      NUMBER CONSTRAINT car_stone_quarry_fk REFERENCES car_quarry (quarry_id),
  farbe_hex      VARCHAR2(7)   CONSTRAINT car_stone_farbe_ck CHECK (REGEXP_LIKE(farbe_hex, '^#[0-9A-F]{6}$')),
  beschreibung   VARCHAR2(1000),
  in_den_thermen VARCHAR2(600),
  quelle         VARCHAR2(400)
)
/
CREATE INDEX car_stone_quarry_ix ON car_stone (quarry_id)
/
COMMENT ON TABLE car_stone IS 'Caracalla: Stein- und Marmorsorten mit Herkunft'
/

-- ------------------------------------------------------------- Material -> Stein
CREATE TABLE car_mat_stone (
  mat_no         NUMBER(3)     NOT NULL,
  stone_id       NUMBER        NOT NULL CONSTRAINT car_mat_stone_fk REFERENCES car_stone (stone_id) ON DELETE CASCADE,
  mat_code       VARCHAR2(20)  NOT NULL,
  hinweis        VARCHAR2(200),
  CONSTRAINT car_mat_stone_pk PRIMARY KEY (mat_no, stone_id)
)
/
CREATE INDEX car_mat_stone_ix ON car_mat_stone (stone_id)
/
COMMENT ON TABLE car_mat_stone IS 'Caracalla: welche Materialnummer der Szene (com.dan.caracalla.geo.Mat) aus welchem Stein ist'
/

-- ------------------------------------------------------------- Regie
CREATE TABLE car_timeline (
  timeline_id    NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_timeline_pk PRIMARY KEY,
  code           VARCHAR2(30)  NOT NULL CONSTRAINT car_timeline_uk UNIQUE,
  name           VARCHAR2(80)  NOT NULL,
  art            VARCHAR2(10)  NOT NULL CONSTRAINT car_timeline_art_ck CHECK (art IN ('FAHRT', 'RUNDGANG', 'DREHBUCH')),
  tag_im_jahr    NUMBER(3)     CONSTRAINT car_timeline_tag_ck CHECK (tag_im_jahr BETWEEN 1 AND 366),
  wasserweg      CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_timeline_ww_ck CHECK (wasserweg IN ('J', 'N')),
  reihenfolge    NUMBER(3),
  eingebaut      CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_timeline_eb_ck CHECK (eingebaut IN ('J', 'N')),
  angelegt       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
/
COMMENT ON TABLE car_timeline IS 'Caracalla: Kamerafahrten, Rundgang und Drehbuch'
/

CREATE TABLE car_clip (
  clip_id        NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_clip_pk PRIMARY KEY,
  timeline_id    NUMBER        NOT NULL CONSTRAINT car_clip_tl_fk REFERENCES car_timeline (timeline_id) ON DELETE CASCADE,
  pos            NUMBER(3)     NOT NULL,
  harter_schnitt CHAR(1) DEFAULT 'J' NOT NULL CONSTRAINT car_clip_hs_ck CHECK (harter_schnitt IN ('J', 'N')),
  stunde_von     NUMBER(4,2),
  stunde_bis     NUMBER(4,2),
  dunst          NUMBER(3,2)   CONSTRAINT car_clip_dunst_ck CHECK (dunst BETWEEN 0 AND 1),
  titel          VARCHAR2(80),
  text           VARCHAR2(600),
  CONSTRAINT car_clip_uk UNIQUE (timeline_id, pos)
)
/
COMMENT ON TABLE car_clip IS 'Caracalla: Einstellungen einer Fahrt mit Sonne, Dunst und Tafel'
/

CREATE TABLE car_key (
  clip_id        NUMBER        NOT NULL CONSTRAINT car_key_clip_fk REFERENCES car_clip (clip_id) ON DELETE CASCADE,
  t_s            NUMBER(7,3)   NOT NULL,
  eye_x NUMBER(9,3) NOT NULL, eye_y NUMBER(9,3) NOT NULL, eye_z NUMBER(9,3) NOT NULL,
  look_x NUMBER(9,3) NOT NULL, look_y NUMBER(9,3) NOT NULL, look_z NUMBER(9,3) NOT NULL,
  CONSTRAINT car_key_pk PRIMARY KEY (clip_id, t_s)
)
/
COMMENT ON TABLE car_key IS 'Caracalla: Schlüsselbilder (Augpunkt, Blickziel) einer Einstellung'
/

-- ------------------------------------------------------------- Gemerkte Blicke
CREATE TABLE car_view (
  view_id        NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_view_pk PRIMARY KEY,
  name           VARCHAR2(80)  NOT NULL CONSTRAINT car_view_uk UNIQUE,
  modus          VARCHAR2(6)   NOT NULL CONSTRAINT car_view_modus_ck CHECK (modus IN ('ORBIT', 'INNEN')),
  eye_x NUMBER(9,3) NOT NULL, eye_y NUMBER(9,3) NOT NULL, eye_z NUMBER(9,3) NOT NULL,
  look_x NUMBER(9,3) NOT NULL, look_y NUMBER(9,3) NOT NULL, look_z NUMBER(9,3) NOT NULL,
  tag_im_jahr    NUMBER(3),
  stunde         NUMBER(4,2),
  dunst          NUMBER(3,2),
  dach           CHAR(1) DEFAULT 'J' NOT NULL CONSTRAINT car_view_dach_ck CHECK (dach IN ('J', 'N')),
  schnitt        CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_view_schn_ck CHECK (schnitt IN ('J', 'N')),
  schnitt_x      NUMBER(5,1),
  zeit           NUMBER(3,2) DEFAULT 0 NOT NULL CONSTRAINT car_view_zeit_ck CHECK (zeit BETWEEN 0 AND 1),
  waermebild     CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_view_wb_ck CHECK (waermebild IN ('J', 'N')),
  wasserweg      CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT car_view_ww_ck CHECK (wasserweg IN ('J', 'N')),
  notiz          VARCHAR2(400),
  angelegt       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
/
COMMENT ON TABLE car_view IS 'Caracalla: gemerkte Blicke mit Kamera, Sonne und Schaltern'
/

-- ------------------------------------------------------------- Baugeschichte
CREATE TABLE car_event (
  event_id       NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT car_event_pk PRIMARY KEY,
  jahr           NUMBER(5)     NOT NULL,
  jahr_bis       NUMBER(5),
  datierung      VARCHAR2(40)  NOT NULL,
  titel          VARCHAR2(80)  NOT NULL,
  text           VARCHAR2(1000),
  zeit           NUMBER(3,2)   CONSTRAINT car_event_zeit_ck CHECK (zeit BETWEEN 0 AND 1),
  room_id        NUMBER CONSTRAINT car_event_room_fk REFERENCES car_room (room_id) ON DELETE SET NULL,
  quelle         VARCHAR2(400),
  quelle_url     VARCHAR2(400),
  CONSTRAINT car_event_bis_ck CHECK (jahr_bis IS NULL OR jahr_bis >= jahr)
)
/
CREATE INDEX car_event_room_ix ON car_event (room_id)
/
COMMENT ON TABLE car_event IS 'Caracalla: Ereignisse der Baugeschichte mit Stelle am Zeitregler und Quelle'
/

-- ------------------------------------------------------------- Spatial
INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES ('CAR_QUARRY', 'LAGE',
        MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.05), MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.05)), 8307)
/
INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES ('CAR_QUARRY', 'WEG',
        MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.05), MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.05)), 8307)
/
COMMIT
/
CREATE INDEX car_quarry_lage_sx ON car_quarry (lage) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 PARAMETERS ('layer_gtype=POINT')
/
CREATE INDEX car_quarry_weg_sx ON car_quarry (weg) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 PARAMETERS ('layer_gtype=LINE')
/
